#!/bin/sh

path="/usr/share/icons/Adwaita/scalable/status/battery-level-10-symbolic.svg"

for battery in /sys/class/power_supply/BAT?
do
	# Get remaining capacity in % and it's status
	capacity=$(cat "$battery"/capacity) || exit
	status=$(cat "$battery"/status)

	[ "$status" = "Discharging" ] && [ "$capacity" -le 25 ] && notify-send --icon $path "Low battery"\
		"Plug in charger"
	case $status in
		Charging) echo CHA: "$capacity"%;;
		Discharging|Full|Unknown) echo BAT: "$capacity"%;;
	esac
done
