#!/bin/sh

file=$1

getSize() {
	size=$(du -b $file|sed "s/\s.*//")
	sleep 1	
	new_size=$(du -b $file|sed "s/\s.*//")
	dif=$(( $new_size - $size ))
	MBps=$(( $dif / 1024 ))
	echo $MBps

}

while true; do echo $(getSize); done

