#!/bin/sh

# Module showing network traffic. Shows how much data has been received (RX) or
# transmitted (TX) since the previous time this script ran. So if run every
# second, gives network traffic per second.

logfile="/root/.cache/netlog"
prevdata=$(cat $logfile) || echo "0 0" > "$logfile"

rxcurrent="$(( $(paste -d '+' /sys/class/net/wlo1/statistics/rx_bytes) ))"
txcurrent="$(( $(paste -d '+' /sys/class/net/wlo1/statistics/tx_bytes) ))"
echo "$rxcurrent $txcurrent" > "$logfile"
printf "∧ %sKiB ∨ %sKiB\\n" \
	"$(( (rxcurrent - ${prevdata%% *}) /1024 ))" \
	"$(( (txcurrent - ${prevdata##* }) /1024 ))"

echo "$rxcurrent $txcurrent" > "$logfile"
