#!/bin/sh

# Fetch and parse newsboat updates 

infoFile="/root/.cache/rss"
unread=$(newsboat -x "reload" -x "print-unread" | sed "s/\s.*//")


[ "$unread" -ne 0 ] && [ "$unread" != "" ] && echo $unread
