#!/bin/sh

interface=$(ip link | grep "3: " | sed "s/3:\s//;s/:.*//")
ssid=$(iwgetid -r)
public_ip=$(cat ~/.cache/ip)
private_ip=$(ip addr | grep -A 3 "3: "| grep inet | sed "s/\/24.*//;s/.*inet\s//")
dc_message="n/a"

case $ssid in
	"") echo $dc_message & echo "" > ~/.cache/ip ;;
	*) echo "$ssid ($public_ip)" ;;
esac
